<?php
declare(strict_types=1);
require dirname(__DIR__, 2) . '/vendor/autoload.php';
use Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\ArtifactCompiler;
use Automattic\BlocksEngine\PhpTransformer\ArtifactCompiler\CapturedDialogProjector;
use Automattic\BlocksEngine\PhpTransformer\WordPress\Runtime;
$cycle = static fn(array $keys, int $initial): array => array('coverage' => 'complete', 'restoration' => 'verified', 'initial' => $initial, 'frames' => array_map(static fn(string $key): array => array('key' => $key, 'fullImage' => $key), $keys));
$inline = $cycle(array('/full/a.png', '/full/b.png', '/full/c.png'), 1);
$inline['selector'] = '#pictures';
$inline['viewport'] = array('width' => 1440, 'height' => 900);
$full = $cycle(array('/full/c.png', '/full/a.png', '/full/b.png'), 2);
$state = array('kind' => 'gallery', 'status' => 'captured', 'gallery' => array('inline' => $inline, 'lightbox' => $full, 'closed' => true, 'selection' => array(1, 2, 0)));
$items = static fn(array $keys): string => implode('', array_map(static fn(string $key): string => '<div><img src="' . $key . '" alt="Image"></div>', $keys));
$html = '<html><head><script data-dla-gallery-runtime>window.captureGallery=true;</script></head><body><section id="pictures" data-dla-gallery data-dla-gallery-source="#pictures" data-dla-gallery-capture-width="1440"><h2>Pictures</h2><div class="gallery carousel"><div id="stage" data-dla-gallery-stage data-dla-gallery-initial="1" data-dla-dialog-trigger="panel" aria-controls="panel">' . $items(array('/inline/a.png', '/inline/b.png', '/inline/c.png')) . '</div><button aria-label="Previous image">Previous</button><button aria-label="Next image">Next</button></div><div id="panel" data-dla-dialog-panel="panel" hidden><div data-dla-gallery-stage>' . $items(array('/full/c.png', '/full/a.png', '/full/b.png')) . '</div></div></section></body></html>';
$report = array('schema' => 'data-liberation/captured-interactions/v1', 'pages' => array(array('sourceUrl' => 'https://neutral.test/', 'states' => array($state))));
$receipt = array('schema' => 'data-liberation/capture-receipt/v1', 'routes' => array(array('url' => 'https://neutral.test/', 'path' => 'website/index.html')));
$files = array('website/index.html' => $html, 'interaction-states.json' => json_encode($report), 'capture-receipt.json' => json_encode($receipt));
$result = (new ArtifactCompiler())->compile(array('entrypoint' => 'website/index.html', 'files' => $files))->toArray();
$markup = $result['source_reports']['wordpress_site_plan']['pages'][0]['canonical_block_markup'] ?? '';
$runtime = new Runtime();
$visit = static function(array $blocks) use (&$visit): array { $all = array(); foreach ($blocks as $block) { $all[] = $block; $all = array_merge($all, $visit($block['innerBlocks'] ?? array())); } return $all; };
$tree = $visit($runtime->parseBlocks($markup));
$carousels = array_values(array_filter($tree, static fn(array $block): bool => str_ends_with($block['blockName'] ?? '', '/authored-carousel')));
$dialogs = array_values(array_filter($tree, static fn(array $block): bool => str_ends_with($block['blockName'] ?? '', '/captured-dialog')));
$assert = static function(bool $condition, string $message): void { if (!$condition) throw new RuntimeException($message); };
$assert(2 === count($carousels), 'Inline and captured lightbox compile through the existing native carousel generator: ' . json_encode(array('count' => count($carousels), 'dialogs' => count($dialogs), 'status' => $result['status'], 'diagnostics' => $result['diagnostics'] ?? array())));
$assert(1 === count($dialogs), 'Image-triggered lightbox compiles through the existing native dialog generator');
$assert(6 === count(array_filter($tree, static fn(array $block): bool => 'core/image' === ($block['blockName'] ?? ''))), 'Every observed frame is an editable image');
$assert(array(array('triggerId' => 'stage', 'indices' => array(1, 2, 0))) === $dialogs[0]['attrs']['gallerySelection'], 'Observed image identities preserve rotated full-cycle selection');
$assert('stage' === ($carousels[0]['attrs']['sourceIdentityAttributes']['id'] ?? ''), 'Source stage trigger identity survives native replacement');
$assert(1 === $carousels[0]['attrs']['initialSlide'] && 2 === $carousels[1]['attrs']['initialSlide'], 'Viewport baseline and lightbox initial state survive compilation');
$assert(!str_contains($markup, 'window.captureGallery'), 'Capture helper is retired, rather than carried as source JavaScript');
$assert($runtime->serializeBlocks($runtime->parseBlocks($markup)) === $markup, 'Native image/dialog tree has a canonical serialize/parse roundtrip');
$wrappedHtml = str_replace(array('<body>', '</body>', '<div><img src="'), array('<body><div class="scroll">', '</div></body>', '<div class="frame active" data-dla-gallery-display="block" hidden style="display:none!important"><img src="'), $html);
$wrappedHtml = str_replace('class="gallery carousel"', 'class="gallery carousel" style="margin-left:auto!important;margin-right:auto!important"', $wrappedHtml);
$wrappedFiles = $files;
$wrappedFiles['website/index.html'] = $wrappedHtml;
$wrapped = (new ArtifactCompiler())->compile(array('entrypoint' => 'website/index.html', 'files' => $wrappedFiles))->toArray();
$wrappedMarkup = $wrapped['source_reports']['wordpress_site_plan']['pages'][0]['canonical_block_markup'] ?? '';
$wrappedTree = $visit($runtime->parseBlocks($wrappedMarkup));
$assert(2 === count(array_filter($wrappedTree, static fn(array $block): bool => str_ends_with($block['blockName'] ?? '', '/authored-carousel'))), 'A thin host and inactive-frame styles cannot flatten a proved directional owner');
$assert(!str_contains($wrappedMarkup, '<!-- wp:gallery '), 'Captured directional behavior remains native navigation rather than a static image collection');
$wrappedCarousels = array_values(array_filter($wrappedTree, static fn(array $block): bool => str_ends_with($block['blockName'] ?? '', '/authored-carousel')));
$assert('auto!important' === ($wrappedCarousels[0]['attrs']['sourceRootGeometry']['margin-left'] ?? null), 'Captured gallery retains the canonical source margin-priority contract');
$report['pages'][0]['states'][0]['gallery']['selection'] = array(0, 1, 2);
$rows = array(); foreach ($files as $path => $content) $rows[] = array('path' => $path, 'content' => 'interaction-states.json' === $path ? json_encode($report) : $content);
$invalid = (new CapturedDialogProjector())->project($rows);
$assert(in_array('captured_gallery_selection_invalid', array_column($invalid['diagnostics'], 'code'), true), 'A shape-valid selection with mismatched image identities remains diagnosed');
echo "Captured gallery producer/consumer contract passed (12 assertions)\n";
